- name: Install netdata
  apt:
    package:
    - netdata
    state: latest
    update_cache: true

- name: Push netdata config
  template:
    src: netdata.conf.j2
    dest: "/etc/netdata/netdata.conf"
  notify: Restart netdata

- name: Push netdata notifications config
  template:
    src: "health_alarm_notify.conf.j2"
    dest: "/etc/netdata/health_alarm_notify.conf"
    mode: 0640
    group: netdata
  notify: Restart netdata

- name: Create netdata config subfolders
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - /etc/netdata/go.d/
  - /etc/netdata/health.d/

- name: Push netdata health.d configs
  template:
    src: "{{ item }}"
    dest: "/etc/netdata/health.d/{{ item | basename }}"
  notify: Restart netdata
  with_fileglob: 'health.d/*.conf'

- name: Enable/start netdata service
  systemd:
    name: netdata
    enabled: true
    state: started

- name: Configure nginx proxy for netdata
  include_role:
    name: apps_nginx
  vars:
    nginx_site:
      src: nginx-netdata.conf.j2
      dst: netdata.conf
